// App
export const OPEN_ADD_NEW_STUDENT_MODAL = "OPEN_ADD_NEW_STUDENT_MODAL";
export const CLOSE_ADD_NEW_STUDENT_MODAL = "CLOSE_ADD_NEW_STUDENT_MODAL";

// Math classroom
export const GET_MATH_STUDENTS_SUCCESS = "GET_MATH_STUDENTS_SUCCESS";
export const GET_MATH_STUDENTS_LOADING = "GET_MATH_STUDENTS_LOADING";
export const GET_MATH_STUDENTS_FAILED = "GET_MATH_STUDENTS_FAILED";

// Physics classroom
export const GET_PHYSICS_STUDENTS_SUCCESS = "GET_PHYSICS_STUDENTS_SUCCESS";
export const GET_PHYSICS_STUDENTS_LOADING = "GET_PHYSICS_STUDENTS_LOADING";
export const GET_PHYSICS_STUDENTS_FAILED = "GET_PHYSICS_STUDENTS_FAILED";

// Chemistry classroom
export const GET_CHEMISTRY_STUDENTS_SUCCESS = "GET_CHEMISTRY_STUDENTS_SUCCESS";
export const GET_CHEMISTRY_STUDENTS_LOADING = "GET_CHEMISTRY_STUDENTS_LOADING";
export const GET_CHEMISTRY_STUDENTS_FAILED = "GET_CHEMISTRY_STUDENTS_FAILED";

// Biology classroom
export const GET_BIOLOGY_STUDENTS_SUCCESS = "GET_BIOLOGY_STUDENTS_SUCCESS";
export const GET_BIOLOGY_STUDENTS_LOADING = "GET_BIOLOGY_STUDENTS_LOADING";
export const GET_BIOLOGY_STUDENTS_FAILED = "GET_BIOLOGY_STUDENTS_FAILED";

// Add new student
export const ADD_NEW_STUDENT_SUCCESS = "ADD_NEW_STUDENT_SUCCESS";
export const ADD_NEW_STUDENT_LOADING = "ADD_NEW_STUDENT_LOADING";
export const ADD_NEW_STUDENT_FAILED = "ADD_NEW_STUDENT_FAILED";

// Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";

// State creator types
export const SUCCESS = "SUCCESS";
export const LOADING = "LOADING";
export const FAILED = "FAILED";